import { BarChart, Bar, CartesianGrid, XAxis, YAxis, Tooltip, ResponsiveContainer, ScatterChart, Scatter, LineChart, Line, Cell } from 'recharts';
var bins = [{ bin: '70–80', count: 3 }, { bin: '80–90', count: 11 }, { bin: '90–100', count: 8 }, { bin: '100–110', count: 4 }];
var scatter = [{ x: 1.2, y: 71 }, { x: 1.8, y: 77 }, { x: 2.1, y: 80 }, { x: 2.8, y: 84 }, { x: 3.3, y: 88 }, { x: 4.1, y: 94 }, { x: 4.8, y: 97 }, { x: 5.5, y: 102 }];
var roc = [{ fpr: 0, tpr: 0 }, { fpr: .08, tpr: .41 }, { fpr: .18, tpr: .63 }, { fpr: .31, tpr: .76 }, { fpr: .49, tpr: .87 }, { fpr: .72, tpr: .94 }, { fpr: 1, tpr: 1 }];
var importance = [{ name: 'Road roughness', value: 0.28 }, { name: 'Oil pressure', value: 0.23 }, { name: 'Vibration', value: 0.19 }, { name: 'Engine temp', value: 0.14 }, { name: 'Mileage', value: 0.10 }, { name: 'Braking events', value: 0.06 }];
export function TempHistogram() { return <ChartBox title="Engine temperature distribution"><ResponsiveContainer width="100%" height={280}><BarChart data={bins}><CartesianGrid strokeDasharray="3 3" stroke="#263246"/><XAxis dataKey="bin" stroke="#94a3b8"/><YAxis stroke="#94a3b8"/><Tooltip contentStyle={{ background: '#0f172a', border: '1px solid #334155' }}/><Bar dataKey="count" fill="#5eead4" radius={[6, 6, 0, 0]}/></BarChart></ResponsiveContainer></ChartBox>; }
export function TempVibrationScatter() { return <ChartBox title="Vibration vs. engine temperature"><ResponsiveContainer width="100%" height={280}><ScatterChart><CartesianGrid stroke="#263246"/><XAxis dataKey="x" name="Vibration" stroke="#94a3b8"/><YAxis dataKey="y" name="Temperature" stroke="#94a3b8"/><Tooltip cursor={{ strokeDasharray: '3 3' }} contentStyle={{ background: '#0f172a', border: '1px solid #334155' }}/><Scatter data={scatter} fill="#a78bfa"/></ScatterChart></ResponsiveContainer></ChartBox>; }
export function RocChart() { return <ChartBox title="ROC curve · illustrative model result"><ResponsiveContainer width="100%" height={280}><LineChart data={roc}><CartesianGrid strokeDasharray="3 3" stroke="#263246"/><XAxis dataKey="fpr" type="number" domain={[0, 1]} stroke="#94a3b8"/><YAxis dataKey="tpr" type="number" domain={[0, 1]} stroke="#94a3b8"/><Tooltip contentStyle={{ background: '#0f172a', border: '1px solid #334155' }}/><Line type="monotone" dataKey="tpr" stroke="#5eead4" strokeWidth={3} dot={false}/></LineChart></ResponsiveContainer></ChartBox>; }
export function ImportanceChart() { return <ChartBox title="Feature importance"><ResponsiveContainer width="100%" height={300}><BarChart data={importance} layout="vertical" margin={{ left: 20, right: 20 }}><CartesianGrid strokeDasharray="3 3" stroke="#263246"/><XAxis type="number" stroke="#94a3b8"/><YAxis dataKey="name" type="category" width={110} stroke="#94a3b8"/><Tooltip contentStyle={{ background: '#0f172a', border: '1px solid #334155' }}/><Bar dataKey="value" radius={[0, 6, 6, 0]}>{importance.map(function (_, i) { return <Cell key={i} fill={i < 2 ? '#5eead4' : '#64748b'}/>; })}</Bar></BarChart></ResponsiveContainer></ChartBox>; }
function ChartBox(_a) {
    var title = _a.title, children = _a.children;
    return <div className="card p-4"><div className="mb-3 text-sm font-medium text-slate-200">{title}</div>{children}</div>;
}
